Update batch
CBIIT/crdc-datahub-backend pull request #111
Opened 2023-10-13 17:11 UTC by knockknockyoo

1. update batch error codes

2023-10-13 17:50 UTC, AustinSMueller approved these changes

2023-10-13 20:09 UTC, vshand11 requested changes

2023-10-13 20:09 UTC, vshand11 commented on services/submission.js
VerifySession or VerifyToken is missing in updateBatch function.

2023-10-16 14:10 UTC, vshand11 commented
Approved.

2023-10-16 14:11 UTC, vshand11 approved these changes
approved

2023-10-16 17:25 UTC, vshand11 commented
Passed my testing with session and token.

2023-10-16 17:45 UTC, merged