CRDCDH - 742
CBIIT/crdc-datahub-backend pull request #248
Opened 2024-01-24 19:30 UTC by knockknockyoo

throw an error for empty comment if admin role and meta/file error contained

2024-01-24 19:32 UTC, knockknockyoo commented on verifier/submission-verifier.js
> +    isValidSubmitAction(role, aSubmission, comment) {
Accidentally added from the previous PR. This is unused function.

2024-01-24 20:39 UTC, vshand11 requested changes
a minor change.

2024-01-24 20:39 UTC, vshand11 commented on verifier/submission-verifier.js
> +            if ([ROLES.ADMIN].includes(role) && isError && (!comment || comment?.trim()?.length === 0)) {
change to ROLES.ADMIN === role

2024-01-25 12:59 UTC, knockknockyoo commented on verifier/submission-verifier.js
> +            if ([ROLES.ADMIN].includes(role) && isError && (!comment || comment?.trim()?.length === 0)) {
updated

2024-01-25 13:48 UTC, vshand11 approved these changes

2024-01-25 13:48 UTC, merged