CRDCDH-1128
CBIIT/crdc-datahub-backend pull request #342
Opened 2024-05-31 20:19 UTC by AustinSMueller

Add "institutions: [String]" parameter to the approveApplication mutation When an application is approved, if it contains institutions not in the database then add them

2024-05-31 20:42 UTC, knockknockyoo requested changes

2024-05-31 20:51 UTC, AustinSMueller commented on services/institution-service.js
> +                if (!existingInstitutions.includes(name)) {
name should always be a String here but even if it is null or undefined it will evaluate to false and will be handled correctly

2024-06-13 18:39 UTC, knockknockyoo commented on services/application.js
> +        await this.institutionService.addNewInstitutions(document.institutions);
Can we move line 248 **await this.institutionService.addNewInstitutions(document.institutions);** into line 251?

2024-06-13 21:47 UTC, AustinSMueller commented on services/institution-service.js
> +        institutionNames = institutionNames instanceof Array ? institutionNames : [];
Updated the array checks to use Array.isArray

2024-06-13 21:47 UTC, AustinSMueller commented on services/institution-service.js
> +                if (!existingInstitutions.includes(name)) {
This code has been rewritten

2024-06-13 21:48 UTC, AustinSMueller commented on services/application.js
> +        await this.institutionService.addNewInstitutions(document.institutions);
Updated the entire addNewInstitutions logic to use a promise

2024-06-13 21:57 UTC, AustinSMueller commented on services/institution-service.js
> +                console.log(`${insertResult?.insertedCount} new institution(s) created in the database`)
I've added an error message in the logs for when a the number of institutions inserted is different from the determined number of new institutions

2024-06-14 11:17 UTC, knockknockyoo approved these changes

2024-06-14 11:17 UTC, merged